defaultNamespace: cert-manager
helm:
  values:
    podAnnotations:
      team: devops
    resources:
       requests:
         cpu: 10m
         memory: 400Mi
       limits:
         cpu: 100m
         memory: 512Mi
    installCRDs: "false"
  # Use a custom location for the Helm chart. This can refer to any go-getter URL.
  # This allows one to download charts from most any location.  Also know that
  # go-getter URL supports adding a digest to validate the download. If repo
  # is set below this field is the name of the chart to lookup
  releaseName: cert-manager
  chart: http://harbor.planetabax.com/chartrepo/verified/charts/cert-manager-1.6.2.tgz